FederationRuntimeEnvironment:
  Rounds: 1
  SynchronousExecution: False
  CommunityFunction: "DVWMicroF1"
  ExecutionTimeMins: 481
  FederationController:
    GRPCServicer:
      hostname/ip: "bdnf.isi.edu"
      port: 30050
  FederationEvaluator:
    GRPCServicer:
      hostname/ip: "bdnf.isi.edu"
      port: 30051
    TFHosts:
      - HostID: "BDNF-Evaluator"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 8898
            taskid: 0
            cpuid: 0
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 8899
            taskid: 0
            cpuid:
            gpuid: 0
            dbconnection:
            is_host_training_leader: True
  TensorflowCluster:
    TFHosts:
      - HostID: "BDNF-DC1"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3222
            taskid: 0
            cpuid: 1
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3223
            taskid: 0
            cpuid:
            gpuid: 1
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 4
            validation_cycle_loss_percentage_threshold: 1
      - HostID: "LEARN-DC1"
        RemoteConfigs:
          hostname/ip: "learn.isi.edu"
          username: "stripeli"
          ld_library_path: ""
          cuda_home: ""
          python_interpreter: "/opt/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "learn.isi.edu"
            port: 3222
            taskid: 0
            cpuid: 1
        WorkerServers:
          - hostname/ip: "learn.isi.edu"
            port: 3223
            taskid: 0
            cpuid: 2
            gpuid:
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC2"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3224
            taskid: 0
            cpuid: 2
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3225
            taskid: 0
            cpuid:
            gpuid: 2
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "LEARN-DC2"
        RemoteConfigs:
          hostname/ip: "learn.isi.edu"
          username: "stripeli"
          ld_library_path: ""
          cuda_home: ""
          python_interpreter: "/opt/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "learn.isi.edu"
            port: 3224
            taskid: 0
            cpuid: 3
        WorkerServers:
          - hostname/ip: "learn.isi.edu"
            port: 3225
            taskid: 0
            cpuid: 4
            gpuid:
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC3"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3226
            taskid: 0
            cpuid: 3
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3227
            taskid: 0
            cpuid:
            gpuid: 3
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "LEARN-DC3"
        RemoteConfigs:
          hostname/ip: "learn.isi.edu"
          username: "stripeli"
          ld_library_path: ""
          cuda_home: ""
          python_interpreter: "/opt/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "learn.isi.edu"
            port: 3226
            taskid: 0
            cpuid: 5
        WorkerServers:
          - hostname/ip: "learn.isi.edu"
            port: 3227
            taskid: 0
            cpuid: 6
            gpuid:
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC4"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3228
            taskid: 0
            cpuid: 4
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3229
            taskid: 0
            cpuid:
            gpuid: 4
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "LEARN-DC4"
        RemoteConfigs:
          hostname/ip: "learn.isi.edu"
          username: "stripeli"
          ld_library_path: ""
          cuda_home: ""
          python_interpreter: "/opt/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "learn.isi.edu"
            port: 3228
            taskid: 0
            cpuid: 7
        WorkerServers:
          - hostname/ip: "learn.isi.edu"
            port: 3229
            taskid: 0
            cpuid: 8
            gpuid:
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC5"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3230
            taskid: 0
            cpuid: 5
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3231
            taskid: 0
            cpuid:
            gpuid: 5
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "LEARN-DC5"
        RemoteConfigs:
          hostname/ip: "learn.isi.edu"
          username: "stripeli"
          ld_library_path: ""
          cuda_home: ""
          python_interpreter: "/opt/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "learn.isi.edu"
            port: 3230
            taskid: 0
            cpuid: 8
        WorkerServers:
          - hostname/ip: "learn.isi.edu"
            port: 3231
            taskid: 0
            cpuid: 9
            gpuid:
            dbconnection:
            local_batch_size: 100
            local_epochs_target_update: 0
            is_host_training_leader: True
            validation_percentage: 5
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
