MetisCatalog:
  host: "128.9.35.22"
  dbname: "metiscatalog"
  username: "metiscatalogdev"
  password: "metiscatalogdev"
MnistDB:
  host: "128.9.35.22"
  dbname: "mnistdb"
  username: "mnistdbdev"
  password: "mnistdbdev"
FMnistDB:
    host: "128.9.35.22"
    dbname: "fmnistdb"
    username: "fmnistdbdev"
    password: "fmnistdbdev"
ExtendedMnistDB:
    host: "128.9.35.22"
    dbname: "extendedmnistdb"
    username: "extendedmnistdbdev"
    password: "extendedmnistdbdev"
Cifar10DB:
  host: "128.9.35.22"
  dbname: "cifar10db"
  username: "cifar10dbdev"
  password: "cifar10dbdev"
Cifar100DB:
  host: "128.9.35.22"
  dbname: "cifar100db"
  username: "cifar100dbdev"
  password: "cifar100dbdev"
Cinic10DB:
  host: "128.9.35.22"
  dbname: "cinic10db"
  username: "cinic10dbdev"
  password: "cinic10dbdev"
ImagenetDB:
  host: "128.9.35.22"
  dbname: "imagenetdb"
  username: "imagenetdbdev"
  password: "imagenetdbdev"