## TODO:(dstripelis) I remember you saying that this folder is old one, if so please confirm so we delete it
FederationEnvironment:
  TerminationSignals:
    FederationRounds: 100
    ExecutionCutoffTimeMins: 100000
    ExecutionCutoffScore: 0.0
  CommunicationProtocol: "SYNCHRONOUS"
  GlobalModelConfig:
    AggregationFunction: "FED_AVG"
    ParticipationRatio: 1
  LocalModelConfig:
    BatchSize: 50
    LocalEpochs: 5
    ValidationPercentage: 0.0
    OptimizerConfig:
      OptimizerName: "VanillaSGD"
      LearningRate: 0.05
      L2Reg: 0.001
  Controller:
    ConnectionConfigs:
      Hostname: "0.0.0.0"
      Username: "foo"
      Password: "bar"
    GRPCServicer:
      Port: 40050
  Learners:
    - LearnerID: "BDNF-1"
      ConnectionConfigs:
        Hostname: "0.0.0.0"
        Username: "foo"
        Password: "bar"
      GRPCServicer:
        Port: 4223
      CudaDevices: []
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidDatasetPath: ""
        TestDatasetPath: ""
    - LearnerID: "BDNF-2"
      ConnectionConfigs:
        Hostname: "0.0.0.0"
        Username: "foo"
        Password: "bar"
      GRPCServicer:
        Port: 4224
      CudaDevices: []
      DatasetConfigs:
        TrainDatasetPath: ""
        ValidDatasetPath: ""
        TestDatasetPath: ""
