FederationRuntimeEnvironment:
  Rounds: 25
  SynchronousExecution: True
  CommunityFunction: "FedAvg"
  ExecutionTimeMins: 100001
  FederationController:
    GRPCServicer:
      hostname/ip: "bdnf.isi.edu"
      port: 30050
  FederationEvaluator:
    GRPCServicer:
      hostname/ip: "bdnf.isi.edu"
      port: 30051
    TFHosts:
      - HostID: "BDNF-Evaluator"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 8898
            taskid: 0
            cpuid: 0
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 8899
            taskid: 0
            cpuid:
            gpuid: 7
            dbconnection:
            local_batch_size: 1
            is_host_training_leader: True
  TensorflowCluster:
    TFHosts:
      #### BDNF.ISI.EDU #####
      - HostID: "BDNF-DC1"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/uniform_datasize_iid_x4clients/without_validation/train_1.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3222
            taskid: 0
            cpuid: 1
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3223
#            taskid: 1
#            cpuid: 2
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3224
            taskid: 0
            cpuid:
            gpuid: 0
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC2"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/uniform_datasize_iid_x4clients/without_validation/train_2.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3225
            taskid: 0
            cpuid: 3
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3226
#            taskid: 1
#            cpuid: 4
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3227
            taskid: 0
            cpuid:
            gpuid: 1
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC3"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/uniform_datasize_iid_x4clients/without_validation/train_3.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3228
            taskid: 0
            cpuid: 5
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3229
#            taskid: 1
#            cpuid: 6
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3230
            taskid: 0
            cpuid:
            gpuid: 2
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC4"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/uniform_datasize_iid_x4clients/without_validation/train_4.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3231
            taskid: 0
            cpuid: 7
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3232
#            taskid: 1
#            cpuid: 8
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3233
            taskid: 0
            cpuid:
            gpuid: 3
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC5"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/adnidata/uniform_datasize_iid_x4clients/without_validation/train_1.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3234
            taskid: 0
            cpuid: 9
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3235
#            taskid: 1
#            cpuid: 10
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3236
            taskid: 0
            cpuid:
            gpuid: 4
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC6"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/adnidata/uniform_datasize_iid_x4clients/without_validation/train_2.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3237
            taskid: 0
            cpuid: 11
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3238
#            taskid: 1
#            cpuid: 12
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3239
            taskid: 0
            cpuid:
            gpuid: 5
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC7"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/adnidata/uniform_datasize_iid_x4clients/without_validation/train_3.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3240
            taskid: 0
            cpuid: 13
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3241
#            taskid: 1
#            cpuid: 14
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3242
            taskid: 0
            cpuid:
            gpuid: 6
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0
      - HostID: "BDNF-DC8"
        RemoteConfigs:
          hostname/ip: "bdnf.isi.edu"
          username: "stripeli"
          ld_library_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/"
          cuda_home: "/usr/local/cuda"
          python_interpreter: "/lfs1/stripeli/metiscondaenv/bin/python3"
        DatasetConfigs:
          train_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/adnidata/uniform_datasize_iid_x4clients/without_validation/train_4.csv"
          validation_dataset_mappings:
          test_dataset_mappings: "/lfs1/stripeli/condaprojects/federatedneuroimaging/projectmetis/resources/config/experiments_configs/brainage/ukbbdata/test.csv"
        ParameterServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3243
            taskid: 0
            cpuid: 15
#          - hostname/ip: "bdnf.isi.edu"
#            port: 3244
#            taskid: 1
#            cpuid: 16
        WorkerServers:
          - hostname/ip: "bdnf.isi.edu"
            port: 3245
            taskid: 0
            cpuid:
            gpuid: 7
            dbconnection:
            local_batch_size: 1
            local_epochs_target_update: 4
            is_host_training_leader: True
            validation_percentage: 0
            validation_cycle_tombstones: 0
            validation_cycle_loss_percentage_threshold: 0